version: '3.1'

services:

  database:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: EmployeeDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 6603:3306
    volumes:
      - "dbdata:/var/lib/mysql"  
    #network_mode: "host"
    #networks: 
     # - mysql-db
   
  web:
    container_name: springboot
    build: .
    depends_on:
      - database
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cicd:3306/EmployeeDB
   # networks: 
    #  - mysql-db
      
#networks: 
 # mysql-db:
  #    driver: bridge
volumes:
  dbdata: