server:
  port: 8082
spring:
  datasource:
    #url: jdbc:mysql://localhost:6603/EmployeeDB
    url: jdbc:mysql://mysql-cicd:3306/EmployeeDB
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #  mvc:#    format:#      date: dd/MM/yyyy
        jackson:    time-zone: Asia/Kolkata    date-format: dd/MM/yyyy hh:mm:ss